/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 drone.glb -t 
*/

import * as THREE from 'three'
import {useGLTF} from '@react-three/drei'
import type {CameraType, WingType} from "./types/drone.ts";

type GLTFResult = {
    nodes: {
        small_part_plate_190: THREE.Mesh
        small_part_scew_fittings91: THREE.Mesh
        small_part_plate_292: THREE.Mesh
        top_board93: THREE.Mesh
        screw_194: THREE.Mesh
        screw_295: THREE.Mesh
        screw_396: THREE.Mesh
        screw_497: THREE.Mesh
        receiver_middle_board98: THREE.Mesh
        receiver_input99: THREE.Mesh
        receiver100: THREE.Mesh
        battery_input101: THREE.Mesh
        battery102: THREE.Mesh
        bottom_frame103: THREE.Mesh
        big_plate_screw_fittings104: THREE.Mesh
        middle_screw_1105: THREE.Mesh
        middle_screw_2106: THREE.Mesh
        middle_screw_3107: THREE.Mesh
        middle_screw_4108: THREE.Mesh
        middle_screw_5109: THREE.Mesh
        middle_screw_6110: THREE.Mesh
        lower_body111: THREE.Mesh
        bottom_venting112: THREE.Mesh
        upper_body113: THREE.Mesh
        camera_base114: THREE.Mesh
        camera_fitting_screw_1115: THREE.Mesh
        camera_fitting_screw_2116: THREE.Mesh
        camera_fitting_screw_3117: THREE.Mesh
        camera_fitting_screw_4118: THREE.Mesh
        camera119: THREE.Mesh
        camera_screw_1120: THREE.Mesh
        camera_screw_2121: THREE.Mesh
        camera_screw_3122: THREE.Mesh
        leg_1123: THREE.Mesh
        leg_2124: THREE.Mesh
        leg_3125: THREE.Mesh
        leg_4126: THREE.Mesh
        prop_1127: THREE.Mesh
        prop_motor_bolt_1128: THREE.Mesh
        motor_1129: THREE.Mesh
        prop_2130: THREE.Mesh
        prop_motor_bolt_2131: THREE.Mesh
        motor_2132: THREE.Mesh
        prop_3133: THREE.Mesh
        prop_motor_bolt_3134: THREE.Mesh
        motor_3135: THREE.Mesh
        prop_motor_bolt_4137: THREE.Mesh
        motor_4138: THREE.Mesh
        prop_bolt_nut_1139: THREE.Mesh
        prop_bolt_nut_2140: THREE.Mesh
        prop_bolt_nut_3141: THREE.Mesh
        prop_bolt_nut_4142: THREE.Mesh
        prop_bolt_cap_1143: THREE.Mesh
        prop_bolt_cap_2144: THREE.Mesh
        prop_bolt_cap_3145: THREE.Mesh
        prop_bolt_cap_4146: THREE.Mesh
        prop_motor_base_1147: THREE.Mesh
        prop_motor_base_2148: THREE.Mesh
        prop_motor_base_3149: THREE.Mesh
        prop_motor_base_4150: THREE.Mesh
        motor_base_screw_a_1151: THREE.Mesh
        motor_base_screw_a_2152: THREE.Mesh
        motor_base_screw_a_3153: THREE.Mesh
        motor_base_screw_a_4154: THREE.Mesh
        motor_base_screw_b_1155: THREE.Mesh
        motor_base_screw_b_2156: THREE.Mesh
        motor_base_screw_b_3157: THREE.Mesh
        motor_base_screw_b_4158: THREE.Mesh
        motor_base_screw_c_1159: THREE.Mesh
        motor_base_screw_c_2160: THREE.Mesh
        motor_base_screw_c_3161: THREE.Mesh
        motor_base_screw_c_4162: THREE.Mesh
        motor_base_screw_d_1163: THREE.Mesh
        motor_base_screw_d_2164: THREE.Mesh
        motor_base_screw_d_3165: THREE.Mesh
        motor_base_screw_d_4166: THREE.Mesh
        prop_4001: THREE.Mesh
        prop_4002: THREE.Mesh
        prop_4003: THREE.Mesh
        prop_1001: THREE.Mesh
        prop_1002: THREE.Mesh
    }
    materials: {
        Material_0: THREE.MeshStandardMaterial
        Material_1: THREE.MeshStandardMaterial
        Material_2: THREE.MeshStandardMaterial
        Material_3: THREE.MeshStandardMaterial
        Material_4: THREE.MeshStandardMaterial
        Material_5: THREE.MeshStandardMaterial
        Material_6: THREE.MeshStandardMaterial
        Material_7: THREE.MeshStandardMaterial
        Material_8: THREE.MeshStandardMaterial
        Material_9: THREE.MeshStandardMaterial
        Material_10: THREE.MeshStandardMaterial
        Material_11: THREE.MeshStandardMaterial
        Material_12: THREE.MeshStandardMaterial
        Material_13: THREE.MeshStandardMaterial
        Material_14: THREE.MeshStandardMaterial
        Material_15: THREE.MeshStandardMaterial
        Material_16: THREE.MeshStandardMaterial
        Material_17: THREE.MeshStandardMaterial
        Material_18: THREE.MeshStandardMaterial
        Material_19: THREE.MeshStandardMaterial
        Material_20: THREE.MeshStandardMaterial
        Material_21: THREE.MeshStandardMaterial
        Material_22: THREE.MeshStandardMaterial
        Material_23: THREE.MeshStandardMaterial
        Material_24: THREE.MeshStandardMaterial
        Material_25: THREE.MeshStandardMaterial
        Material_26: THREE.MeshStandardMaterial
        Material_27: THREE.MeshStandardMaterial
        Material_28: THREE.MeshStandardMaterial
        Material_29: THREE.MeshStandardMaterial
        Material_30: THREE.MeshStandardMaterial
        Material_31: THREE.MeshStandardMaterial
        Material_32: THREE.MeshStandardMaterial
        Material_33: THREE.MeshStandardMaterial
        Material_34: THREE.MeshStandardMaterial
        Material_35: THREE.MeshStandardMaterial
        Material_36: THREE.MeshStandardMaterial
        Material_37: THREE.MeshStandardMaterial
        Material_38: THREE.MeshStandardMaterial
        Material_39: THREE.MeshStandardMaterial
        Material_40: THREE.MeshStandardMaterial
        Material_41: THREE.MeshStandardMaterial
        Material_42: THREE.MeshStandardMaterial
        Material_43: THREE.MeshStandardMaterial
        Material_44: THREE.MeshStandardMaterial
        Material_45: THREE.MeshStandardMaterial
        Material_47: THREE.MeshStandardMaterial
        Material_48: THREE.MeshStandardMaterial
        Material_49: THREE.MeshStandardMaterial
        Material_50: THREE.MeshStandardMaterial
        Material_51: THREE.MeshStandardMaterial
        Material_52: THREE.MeshStandardMaterial
        Material_53: THREE.MeshStandardMaterial
        Material_54: THREE.MeshStandardMaterial
        Material_55: THREE.MeshStandardMaterial
        Material_56: THREE.MeshStandardMaterial
        Material_57: THREE.MeshStandardMaterial
        Material_58: THREE.MeshStandardMaterial
        Material_59: THREE.MeshStandardMaterial
        Material_60: THREE.MeshStandardMaterial
        Material_61: THREE.MeshStandardMaterial
        Material_62: THREE.MeshStandardMaterial
        Material_63: THREE.MeshStandardMaterial
        Material_64: THREE.MeshStandardMaterial
        Material_65: THREE.MeshStandardMaterial
        Material_66: THREE.MeshStandardMaterial
        Material_67: THREE.MeshStandardMaterial
        Material_68: THREE.MeshStandardMaterial
        Material_69: THREE.MeshStandardMaterial
        Material_70: THREE.MeshStandardMaterial
        Material_71: THREE.MeshStandardMaterial
        Material_72: THREE.MeshStandardMaterial
        Material_73: THREE.MeshStandardMaterial
        Material_74: THREE.MeshStandardMaterial
        Material_75: THREE.MeshStandardMaterial
        Material_76: THREE.MeshStandardMaterial
        Material_46: THREE.MeshStandardMaterial
    }
}

interface Props {
    wingtype: WingType;
    cameratype: CameraType;
}

export function ModelDrone({wingtype, cameratype}: Props) {
    const {nodes, materials} = useGLTF('/scene-transformed.glb') as unknown as GLTFResult
    return (
        <group dispose={null}>
            <mesh geometry={nodes.small_part_plate_190.geometry} material={materials.Material_0}/>
            <mesh geometry={nodes.small_part_scew_fittings91.geometry} material={materials.Material_1}/>
            <mesh geometry={nodes.small_part_plate_292.geometry} material={materials.Material_2}/>
            <mesh geometry={nodes.top_board93.geometry} material={materials.Material_3}/>
            <mesh geometry={nodes.screw_194.geometry} material={materials.Material_4}/>
            <mesh geometry={nodes.screw_295.geometry} material={materials.Material_5}/>
            <mesh geometry={nodes.screw_396.geometry} material={materials.Material_6}/>
            <mesh geometry={nodes.screw_497.geometry} material={materials.Material_7}/>
            <mesh geometry={nodes.receiver_middle_board98.geometry} material={materials.Material_8}/>
            <mesh geometry={nodes.receiver_input99.geometry} material={materials.Material_9}/>
            <mesh geometry={nodes.receiver100.geometry} material={materials.Material_10}/>
            <mesh geometry={nodes.battery_input101.geometry} material={materials.Material_11}/>
            <mesh geometry={nodes.battery102.geometry} material={materials.Material_12}/>
            <mesh geometry={nodes.bottom_frame103.geometry} material={materials.Material_13}/>
            <mesh geometry={nodes.big_plate_screw_fittings104.geometry} material={materials.Material_14}/>
            <mesh geometry={nodes.middle_screw_1105.geometry} material={materials.Material_15}/>
            <mesh geometry={nodes.middle_screw_2106.geometry} material={materials.Material_16}/>
            <mesh geometry={nodes.middle_screw_3107.geometry} material={materials.Material_17}/>
            <mesh geometry={nodes.middle_screw_4108.geometry} material={materials.Material_18}/>
            <mesh geometry={nodes.middle_screw_5109.geometry} material={materials.Material_19}/>
            <mesh geometry={nodes.middle_screw_6110.geometry} material={materials.Material_20}/>
            <mesh geometry={nodes.lower_body111.geometry} material={materials.Material_21}/>
            <mesh geometry={nodes.bottom_venting112.geometry} material={materials.Material_22}/>
            <mesh geometry={nodes.upper_body113.geometry} material={materials.Material_23}/>
            <mesh geometry={nodes.leg_1123.geometry} material={materials.Material_33}/>
            <mesh geometry={nodes.leg_2124.geometry} material={materials.Material_34}/>
            <mesh geometry={nodes.leg_3125.geometry} material={materials.Material_35}/>
            <mesh geometry={nodes.leg_4126.geometry} material={materials.Material_36}/>
            <mesh geometry={nodes.prop_motor_bolt_1128.geometry} material={materials.Material_38}/>
            <mesh geometry={nodes.motor_1129.geometry} material={materials.Material_39}/>
            <mesh geometry={nodes.prop_motor_bolt_2131.geometry} material={materials.Material_41}/>
            <mesh geometry={nodes.motor_2132.geometry} material={materials.Material_42}/>
            <mesh geometry={nodes.prop_motor_bolt_3134.geometry} material={materials.Material_44}/>
            <mesh geometry={nodes.motor_3135.geometry} material={materials.Material_45}/>
            <mesh geometry={nodes.prop_motor_bolt_4137.geometry} material={materials.Material_47}/>
            <mesh geometry={nodes.motor_4138.geometry} material={materials.Material_48}/>
            <mesh geometry={nodes.prop_bolt_nut_1139.geometry} material={materials.Material_49}/>
            <mesh geometry={nodes.prop_bolt_nut_2140.geometry} material={materials.Material_50}/>
            <mesh geometry={nodes.prop_bolt_nut_3141.geometry} material={materials.Material_51}/>
            <mesh geometry={nodes.prop_bolt_nut_4142.geometry} material={materials.Material_52}/>
            <mesh geometry={nodes.prop_bolt_cap_1143.geometry} material={materials.Material_53}/>
            <mesh geometry={nodes.prop_bolt_cap_2144.geometry} material={materials.Material_54}/>
            <mesh geometry={nodes.prop_bolt_cap_3145.geometry} material={materials.Material_55}/>
            <mesh geometry={nodes.prop_bolt_cap_4146.geometry} material={materials.Material_56}/>
            <mesh geometry={nodes.prop_motor_base_1147.geometry} material={materials.Material_57}/>
            <mesh geometry={nodes.prop_motor_base_2148.geometry} material={materials.Material_58}/>
            <mesh geometry={nodes.prop_motor_base_3149.geometry} material={materials.Material_59}/>
            <mesh geometry={nodes.prop_motor_base_4150.geometry} material={materials.Material_60}/>
            <mesh geometry={nodes.motor_base_screw_a_1151.geometry} material={materials.Material_61}/>
            <mesh geometry={nodes.motor_base_screw_a_2152.geometry} material={materials.Material_62}/>
            <mesh geometry={nodes.motor_base_screw_a_3153.geometry} material={materials.Material_63}/>
            <mesh geometry={nodes.motor_base_screw_a_4154.geometry} material={materials.Material_64}/>
            <mesh geometry={nodes.motor_base_screw_b_1155.geometry} material={materials.Material_65}/>
            <mesh geometry={nodes.motor_base_screw_b_2156.geometry} material={materials.Material_66}/>
            <mesh geometry={nodes.motor_base_screw_b_3157.geometry} material={materials.Material_67}/>
            <mesh geometry={nodes.motor_base_screw_b_4158.geometry} material={materials.Material_68}/>
            <mesh geometry={nodes.motor_base_screw_c_1159.geometry} material={materials.Material_69}/>
            <mesh geometry={nodes.motor_base_screw_c_2160.geometry} material={materials.Material_70}/>
            <mesh geometry={nodes.motor_base_screw_c_3161.geometry} material={materials.Material_71}/>
            <mesh geometry={nodes.motor_base_screw_c_4162.geometry} material={materials.Material_72}/>
            <mesh geometry={nodes.motor_base_screw_d_1163.geometry} material={materials.Material_73}/>
            <mesh geometry={nodes.motor_base_screw_d_2164.geometry} material={materials.Material_74}/>
            <mesh geometry={nodes.motor_base_screw_d_3165.geometry} material={materials.Material_75}/>
            <mesh geometry={nodes.motor_base_screw_d_4166.geometry} material={materials.Material_76}/>
            <mesh geometry={nodes.prop_4003.geometry} material={materials.Material_46} position={[-0.092, 0, -0.154]}
                  rotation={[-Math.PI, 1.067, -Math.PI]}/>
            <mesh geometry={nodes.prop_1001.geometry} material={materials.Material_37} position={[0.228, 0, 0.163]}
                  rotation={[0, -1.411, 0]}/>
            <mesh geometry={nodes.prop_1002.geometry} material={materials.Material_37} position={[0, 0, -0.002]}
                  rotation={[-Math.PI, 1.444, -Math.PI]}/>
            <mesh geometry={nodes.prop_3133.geometry} material={materials.Material_43}/>

            {cameratype === true &&
                <>
                    <mesh geometry={nodes.camera_base114.geometry} material={materials.Material_24}/>
                    <mesh geometry={nodes.camera_fitting_screw_1115.geometry} material={materials.Material_25}/>
                    <mesh geometry={nodes.camera_fitting_screw_2116.geometry} material={materials.Material_26}/>
                    <mesh geometry={nodes.camera_fitting_screw_3117.geometry} material={materials.Material_27}/>
                    <mesh geometry={nodes.camera_fitting_screw_4118.geometry} material={materials.Material_28}/>
                    <mesh geometry={nodes.camera119.geometry} material={materials.Material_29}/>
                    <mesh geometry={nodes.camera_screw_1120.geometry} material={materials.Material_30}/>
                    <mesh geometry={nodes.camera_screw_2121.geometry} material={materials.Material_31}/>
                    <mesh geometry={nodes.camera_screw_3122.geometry} material={materials.Material_32}/>
                </>}


            {wingtype === 'quadruples' && <>
                <mesh geometry={nodes.prop_2130.geometry} material={materials.Material_40} position={[-8.09, 0, 4.005]}
                      rotation={[0, -0.842, 0]}/>
                <mesh geometry={nodes.prop_1127.geometry} material={materials.Material_37}
                      position={[-7.493, -0.022, -3.797]} rotation={[0, 0.754, 0]}/>
                <mesh geometry={nodes.prop_4001.geometry} material={materials.Material_46}
                      position={[-2.529, 0, -9.839]} rotation={[Math.PI, -1.088, Math.PI]}/>
                <mesh geometry={nodes.prop_4002.geometry} material={materials.Material_46} position={[8.35, 0, -3.868]}
                      rotation={[-Math.PI, 0.219, -Math.PI]}/>
            </>
            }

        </group>
    )
}

useGLTF.preload('/scene-transformed.glb')
